version: '3.8'

services:

  dbpostgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online-shop

      